version: '2'

services:
  myapp:
    build: ./
    ports:
      - 3000:3000
    links:
      - database
    volumes:
      - .:/usr/src/app
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - 27017:27017
